### ISSUE TITLE
Feature request: ability to link without header warning

### ISSUE THREAD

**Issue by dellis23** [Lokaltog/git-man-page-generator-legacy#2]
After a couple of successful "gets" on my co-workers, they are not falling for it anymore.  It would be nice to have an option when generating the link to not show warnings.

As a bonus feature, configuring the main site to still show from other domains would be nice.  I'd like to get a domain that is a little sneakier and point it there too :-)

**Comment by dellis23** [comment]
I just realized this is open source.  I can do whatever I want!

Muwahahahahaha.

**Comment by kernc** [comment]
:+1: on this issue. Should be some inconspicuous URL fragment or something.

**Comment by dellis23** [comment]
@kernc Please see this link: http://git-scms.com/docs/segment-commit#9d31455b47665087191b7d76feb43938

**Comment by kernc** [comment]
Perfect, thanks!
